gantt
    title Zeitplan
    dateFormat YYYY-MM-DD
    axisformat %Y-%m

    section Allgmein
    Kickoff                     : milestone, 2024-10-01,
    Vorbereitungen              : 2024-09-16, 2w
    Offizielle Bearbeitung      : 2024-10-01, 2025-03-31
    Abschluss                   : milestone, 2025-03-10,
    Zeitreserve                 : 2025-03-10, 2025-03-31

    section Schreibarbeit
    Thema und Expose            : 2024-10-01, 2w
    Expose final                : milestone,
    Schreibkonzept              : 2w
    Schreiben                   : 16w
    Vorversion                  : milestone,
    Korrektur                   : 2w
    Finale Version              : milestone,
    Drucken und Binden          : 1w


    section Forschung & Entwicklung
    Observation                     : 2024-10-01, 3w
    State-Of-The-Art analyisiert    : milestone,
    Modellierung                    : 6w
    Grundlegende Architektur        : milestone,
    Implementierung                 : 6w
    Funktionsfähiger Prototyp       : milestone,
    Evaluation                      : 4w
    Bewertung des Prototyps         : milestone,



